### PR TITLE
WIP make table and try to figure out how the app starts

### PR DESCRIPTION
**Pull request by spielhoelle**
Plz suggestions for the Readme file how the app is started in development mode, describe routes and explain ux-flow

### CODE REVIEW

**Comment by spielhoelle** [comment]
Hey could somebody give me some feedback?!  When I don’t know how to start the app, I can’t contribute :(

**Comment by josearmandojacq** [comment]
we will start working on the readme.md ✌🏽✌🏽

**Comment by spielhoelle** [comment]
https://media.giphy.com/media/3ohfFDm8HGVnWGkMdq/giphy.gif

**Comment by aemal** [comment]
In a few hours we will ping you with the new change, this morning I also had a talk with Val about it, I was going to use a boiler plate, but we will keep things simple and use create-react-app and the Backend as we have already built, by COB today we should have the readme file with instructions, hopefully 😉

**Pull request closed without merging**
